# Generated by Django 4.2.3 on 2023-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profession', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Employee last name')),
                ('prenom', models.CharField(max_length=120, verbose_name='Employee first name')),
                ('email_address', models.EmailField(default='example@example.com', max_length=254, verbose_name='Employee Email')),
                ('date', models.DateTimeField(verbose_name='Date of problem')),
                ('department', models.CharField(max_length=120)),
                ('equipement', models.CharField(max_length=120, verbose_name='Type of equipment')),
                ('probleme', models.TextField()),
                ('solution', models.TextField()),
                ('traitement', models.CharField(default='', max_length=120, verbose_name='Etat de traitement')),
                ('writed', models.ManyToManyField(blank=True, to='Main.tech')),
            ],
        ),
    ]
