# Generated by Django 4.2.3 on 2023-07-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='probleme',
            new_name='problem',
        ),
        migrations.AlterField(
            model_name='employe',
            name='email_address',
            field=models.EmailField(default='example@example.com', max_length=254, verbose_name='Employe Email'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nom',
            field=models.CharField(max_length=120, verbose_name='Employe last name'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='prenom',
            field=models.CharField(max_length=120, verbose_name='Employe first name'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='traitement',
            field=models.CharField(default='', max_length=120, verbose_name='traitement'),
        ),
    ]
