# Generated by Django 4.2.3 on 2023-07-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_rename_probleme_employe_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
