# Generated by Django 4.2.3 on 2023-07-11 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_tech_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='date',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='equipement',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='traitement',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='profession',
        ),
        migrations.AddField(
            model_name='tech',
            name='site',
            field=models.CharField(default='noName', max_length=120),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ticket Title')),
                ('ticket_date', models.DateTimeField(verbose_name='Ticket Date')),
                ('material', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('solution', models.TextField(blank=True)),
                ('status', models.CharField(max_length=120)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.employe')),
                ('writed', models.ManyToManyField(blank=True, to='Main.tech')),
            ],
        ),
    ]
