# Generated by Django 4.2.3 on 2023-07-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_employe_date_remove_employe_equipement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
