# Generated by Django 4.2.3 on 2023-07-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_employe_site_employe_telephone_tech_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='matricule',
            field=models.CharField(default='AB000', max_length=120, verbose_name='employe matricule'),
        ),
    ]
