# Generated by Django 4.2.3 on 2023-07-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_employe_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='username',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='tech',
            name='email_address',
            field=models.EmailField(default='example@example.com', max_length=254, verbose_name='Employee Email'),
        ),
    ]
