# Generated by Django 4.2.3 on 2023-07-21 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0009_tech_is_active_tech_is_staff_tech_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='writed1',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
