# Generated by Django 4.2.3 on 2023-07-21 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0010_ticket_writed1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='writed1',
            field=models.ManyToManyField(blank=True, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
