# Generated by Django 4.2.3 on 2023-07-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_ticket_writed1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed Date'),
        ),
    ]
