# Generated by Django 4.2.3 on 2023-07-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_ticket_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Completed Date'),
        ),
    ]
